CREATE DATABASE IF NOT EXISTS QEMS;

USE QEMS;

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    SALARY INT NOT NULL check (SALARY>=1500),
    DEPTID INT NOT NULL REFERENCES DEPARTMENT(DEPTID)
);

CREATE TABLE DEPARTMENT (
    DEPTID INT PRIMARY KEY AUTO_INCREMENT,
    DEPTNAME VARCHAR(30) NOT NULL
);

INSERT INTO DEPARTMENT (DEPTNAME) VALUES ('HR');
INSERT INTO DEPARTMENT (DEPTNAME) VALUES ('SALES');
INSERT INTO DEPARTMENT (DEPTNAME) VALUES ('ACCOUNTS');
